eureka:
  client:
    service-url:
      #默认的服务注册地址
      defaultZone: http://192.168.1.220:8761/eureka/

spring:
  data:
    mongodb:
      uri: mongodb://192.168.1.223:27017/test
  redis:
    host: 192.168.1.222
    port: 6379