server:
  port: 9000
spring:
  profiles:
    active: dev
  application:
    name: auth-server
eureka:
  instance:
    #虚拟主机名称
    virtual-host-name: auth-server
    #心跳时间间隔
    lease-renewal-interval-in-seconds: 10
    #无心跳多久后,该服务失效
    lease-expiration-duration-in-seconds: 30
    appname: auth-server
    #Server实例ID
    instance-id: ${spring.application.name}:${random.value}
